app/src/main/res/font/yeogida_font.xml

[FEAT] 나눔손글씨 손편지체 추가

---

app/src/main/java/com/starters/yeogida/data/remote/response/BaseResponse.kt
app/src/main/java/com/starters/yeogida/util/ContextExt.kt
app/src/main/java/com/starters/yeogida/util/CustomEnqueue.kt
app/src/main/java/com/starters/yeogida/util/ResourceExt.kt

close #27 
- 확장함수 추가
- base response 추가
- custom enqueue 추가

[FEAT] Util 추가

---

app/src/main/java/com/starters/yeogida/data/local/PlaceData.kt

ui/#19
#19 
- PlaceData 추가
- 30번 pr에서 commit을 안했어요... 죄송합니다.... pr하나 추가요...

[UI] 장소 둘러보기 화면..

---

app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
app/src/main/res/drawable/ic_next.xml
app/src/main/res/layout/fragment_mypage.xml
app/src/main/res/values/strings.xml

close #13 
- 레이아웃만 추가
- dialog는 custom으로 따로 뺄 예정이라 아직 합치지 않음

[UI] 마이페이지

---

app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageViewModel.kt
app/src/main/java/com/starters/yeogida/presentation/mypage/MypageFragment.kt
app/src/main/res/layout/dialog_custom.xml
app/src/main/res/layout/fragment_mypage.xml
app/src/main/res/navigation/main_navigation.xml

close #34 
- 로그아웃 
- 회원탈퇴 다이얼로그
- Navigation 설정

[FEAT] 마이페이지 로그아웃, 회원탈퇴

---

app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
app/src/main/java/com/starters/yeogida/util/UriUtil.kt

close #57  
- 권한 처리 버그 수정
- 이미지 크기 압축 코드 추가
- Bitmap을 Uri로 변경하는 함수 UriUtil로 이동

[FIX] 프로필 이미지 버그

---

app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceMapFragment.kt
app/src/main/res/layout/fragment_alarm.xml
app/src/main/res/layout/fragment_around_place.xml
app/src/main/res/layout/fragment_around_place_map.xml

close #73 
- imageView로 따로 뺏던 뒤로 가기 버튼을 navigation icon으로 변경했습니다.
- 여행지 추가 화면은 Tool bar를 따로 만들지 않아 ImageView 뒤로가기를 수정하지 않았습니다.

[REFACTOR] navigation icon 적용

---

app/src/main/java/com/starters/yeogida/data/local/BestTravelerData.kt
app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt

[REFACTOR] 변수 이름 변경

---

app/src/main/java/com/starters/yeogida/YeogidaApplication.kt
app/src/main/java/com/starters/yeogida/YeogidaDataStore.kt
app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/starters/yeogida/presentation/splash/SplashViewModel.kt
app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt

close #85 
- DataStore에 memberId 값 추가에 따른 회원관련 코드 수정 하였습니다.
- 로그인, 회원가입 시에 memberId 값 저장코드를 추가하였습니다.
- 부적절한 토큰, 유효하지 않은 토큰, 로그아웃, 회원탈퇴 시에 값 제거 코드를 추가하였습니다.

[FEAT] DataStore memberId 값 추가에 따른 코드 추가

---

app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/res/layout/fragment_place_detail.xml
app/src/main/res/layout/item_comment.xml

- close #84 
- viewBindingAdapter 추가
- data store에 저장된 memberId와 댓글의 memberId를 비교하여 신고 / 삭제를 나타냄

[FEAT] 댓글 조회

---

app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
app/src/main/java/com/starters/yeogida/data/remote/request/place/CommentRequest.kt
app/src/main/java/com/starters/yeogida/data/remote/response/place/AddCommentResponse.kt
app/src/main/java/com/starters/yeogida/presentation/around/PlaceSortBottomSheetFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/TripSortBottomSheetFragment.kt
app/src/main/java/com/starters/yeogida/presentation/common/OnItemClick.kt
app/src/main/java/com/starters/yeogida/presentation/common/SortAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/java/com/starters/yeogida/presentation/trip/RegionAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt
app/src/main/res/layout/fragment_place_detail.xml
app/src/main/res/layout/item_comment.xml

close #62 
- 댓글 추가 api 연결
- 댓글 삭제 api 연결
- 댓글 목록 로직 변경
- header는 initAuthorization()에서 data store값을 변수에 저장하고 변수를 사용
- itemClick 부분 수정
- 댓글 목록 로직은 다른 이슈와 branch에서 진행해야 하지만 데모로 인해 여기서 진행했습니다.
- 댓글에 path로 있는 placeId는 아직 장소 화면을 연결하지 않아 현재 더미로 넣었습니다.

[NETWORK] 댓글 추가, 삭제 API

---

app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
app/src/main/java/com/starters/yeogida/data/api/TripService.kt
app/src/main/java/com/starters/yeogida/data/remote/request/place/CommentRequest.kt
app/src/main/java/com/starters/yeogida/data/remote/response/place/AddCommentResponse.kt
app/src/main/java/com/starters/yeogida/data/remote/response/trip/PostTripResponse.kt
app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
app/src/main/java/com/starters/yeogida/presentation/around/PlaceSortBottomSheetFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/TripSortBottomSheetFragment.kt
app/src/main/java/com/starters/yeogida/presentation/common/OnItemClick.kt
app/src/main/java/com/starters/yeogida/presentation/common/SortAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/common/ViewBindingAdpater.kt
app/src/main/java/com/starters/yeogida/presentation/place/CommentAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/java/com/starters/yeogida/presentation/trip/AddTripFragment.kt
app/src/main/java/com/starters/yeogida/presentation/trip/RegionAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt
app/src/main/res/layout/fragment_add_trip.xml
app/src/main/res/layout/fragment_place_detail.xml
app/src/main/res/layout/item_comment.xml

close #89 
- 여행지 추가 api 연결
- multipart 사용
- 이미지 권한은 다른 이슈에서 진행하겠습니다.
- 이전 작업에서 branch를 변경하지 않고 작업해 전 commit이 같이 올라왔습니다. 앞으로 조심하겠습니다ㅜ
- 여행지 부분 파일 변경만 확인해주세요.

[NETWORK] 여행지 추가

---

app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
app/src/main/java/com/starters/yeogida/data/local/PlaceData.kt
app/src/main/java/com/starters/yeogida/data/remote/response/place/PlaceListResponse.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/common/TextBindingAdapter.kt
app/src/main/res/layout/fragment_around_place.xml
app/src/main/res/layout/item_place.xml

close #50 
- 장소 둘러보기 api 연결
- 장소 둘러보기 엠티뷰 로직 추가
- 장소 둘러보기 제약 변경

[NETWORK] 장소 둘러보기

---

app/.gitignore
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/starters/yeogida/YeogidaFirebaseMessagingService.kt
build.gradle

close #96 
- fcm 관련 build 파일 변경
- fcm service 객체 생성
- fcm은 새로운 부분이 있을 것 같아 주석에 설명을 추가했습니다.
- sendNotification에 알림 생성 코드를 추가했습니다.
- firebase에서 알림 오는 거 확인했습니다.
- google-service.json 파일을 .gitignore에 포함했습니다.
- sendNotification은 서버 통신 및 로직 설계 후에 변경 예정

[FEAT] 알림 초기 세팅

---

app/src/main/java/com/starters/yeogida/presentation/mypage/MyPageFragment.kt
app/src/main/java/com/starters/yeogida/presentation/mypage/MyTripFragment.kt
app/src/main/res/layout/fragment_my_page.xml
app/src/main/res/layout/fragment_my_trip.xml
app/src/main/res/navigation/nav_mypage.xml

close #100 
- 나의 여행지 UI
- navigation 연결
- 맨 위로 가기, 뒤로 가기 구현
- 더미데이터 추가
- 엠티뷰 로직은 서버 통신 때 진행

[UI] 나의 여행지

---

app/build.gradle
app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/Place.kt

close #107 
- 클러스터링 구현
- 클러스터링 임시 데이터 추가
- 클러스터링 dependency 추가
- 클러스터링은 onMarkerClick이 적용되지 않아 cluster manager에서 제공하는 setOnClusterItemClickListener 사용
- 데이터 형식이 나오지 않아 임시로 세팅했습니다. 서버가 나온 후에 서버 연결 및 로직 진행하겠습니다.

[FEAT] 클러스터링 초기 세팅

---

app/src/main/java/com/starters/yeogida/presentation/trip/RegionBottomSheetFragment.kt

close #115 
- 여행지 추가 지역 바텀 시트 추가

[FEAT] 지역 데이터 추가

---

app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
app/src/main/java/com/starters/yeogida/presentation/like/LikeTripViewModel.kt

close #120 
- ViewModel 클릭 이벤트 수정

[FIX] 여기 좋아 클릭 버그

---

app/src/main/java/com/starters/yeogida/data/remote/request/LoginRequestData.kt
app/src/main/java/com/starters/yeogida/presentation/user/JoinActivity.kt
app/src/main/java/com/starters/yeogida/presentation/user/LoginActivity.kt

close #123 
- fcm 토큰 받아오기
- fcm 토큰값 JoinActivity, LoginActivity에 적용
- getFCMToken 함수에서 FirebaseMessaging 사용해서 토큰 받아옴
- 토큰 받은 후 로그인 처리를 하기 위해 getToken을 가장 먼저 호출
- token값은 JoinActivity로 전달해서 postLogin에서 사용

[NETWORK] FCM 토큰

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/starters/yeogida/MainActivity.kt
app/src/main/java/com/starters/yeogida/YeogidaFirebaseMessagingService.kt
app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt

close #125 
- 서버 알림 통신
- 알림에 따른 화면 전환
- 화면 전환에 따른 데이터 전달
- 알림 포그라운드에서도 작동하도록
- 알림 type에 따라 MainActivity에서 화면 전환 및 데이터 전달
- 푸시 알림에 필요한 버전 처리 추가
- 포그라운드 푸시 알림을 위해 android:launchMode와 onNewIntent 사용
- 버전 처리 확인을 위해 낮은 버전에서도 돌려봐야 할 것 같습니다.

[FEAT] 푸시 알림

---

app/src/main/java/com/starters/yeogida/data/local/TripLikeUserData.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceViewModel.kt
app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserListAdapter.kt
app/src/main/res/layout/fragment_trip_like_user.xml
app/src/main/res/layout/item_trip_like_user.xml
app/src/main/res/navigation/nav_place.xml
app/src/main/res/values/strings.xml

close #136 
- 좋아요 누른 유저들 목록 UI
- 아이템 레이아웃
- 어댑터 연결
- 클릭 시 유저 상세로 이동하기 위해 memberId 사용하여 이벤트 연결
- 유저 상세 연결은 여행지 상세 통신 완료되는 대로 연결하겠습니다.

[UI] 여행지 상세 좋아요 누른 유저 목록

---

app/src/main/java/com/starters/yeogida/data/api/AroundService.kt
app/src/main/java/com/starters/yeogida/data/remote/response/place/ClusterPlaceResponse.kt
app/src/main/java/com/starters/yeogida/network/YeogidaClient.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt

close #132 
- 둘러보기 메인 API 연결 (data, service 추가)
- 둘러보기 마커 추가
- 후에 커스텀 마커를 진행할 수도 있어 참고할 코드를 주석처리 해두었습니다.

[NETWORK] 둘러보기 화면

---

app/src/main/java/com/starters/yeogida/data/api/AroundService.kt
app/src/main/java/com/starters/yeogida/data/remote/response/place/ClusterMarkerResponse.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/Place.kt
app/src/main/java/com/starters/yeogida/presentation/around/PlaceBottomSheetAdapter.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceActivity.kt
app/src/main/res/layout/fragment_place_bottom_sheet.xml
app/src/main/res/layout/item_bottom_sheet_place.xml

close #134 
- 둘러보기 마커 api 추가
- 마커 아이템 클릭 시 화면 이동
- textView width 변경
- PlaceActivity에서 이동 화면에 따라 type으로 분류

[NETWORK] 장소 둘러보기 마커

---

app/src/main/java/com/starters/yeogida/presentation/mypage/NotificationSettingFragment.kt
app/src/main/java/com/starters/yeogida/presentation/mypage/SettingFragment.kt
app/src/main/res/layout/fragment_notification_setting.xml
app/src/main/res/layout/fragment_setting.xml
app/src/main/res/navigation/nav_mypage.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

close #148 
- 알림 설정 화면 
- 알림 설정 화면 이동

[UI] 알림 설정 화면

---

app/src/main/java/com/starters/yeogida/data/api/HomeService.kt
app/src/main/java/com/starters/yeogida/data/remote/response/HomeTripResponseResponse.kt
app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt

close #162 
- 최근 게시글 관련 data, service 생성
- 최근 게시글 관련 api, adapter 연결
- 월간 best 여행지와 팔로잉의 최근 여행지의 data를 같이 쓰기 위해서 rename을 진행했습니다.

[NETWORK] 팔로잉의 최근 게시글

---

app/src/main/java/com/starters/yeogida/presentation/home/HomeFragment.kt
app/src/main/java/com/starters/yeogida/presentation/home/TripAdapter.kt

close #164 
- TripAdapter에 itemClick 추가
- 월간 best 여행지, 팔로잉의 최근 여행지 클릭 시 해당 여행지로 이동

[FEAT] 홈 화면 로직

---

app/src/main/java/com/starters/yeogida/data/api/PlaceService.kt
app/src/main/java/com/starters/yeogida/data/api/TripService.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt

close #169 
- 여행지 삭제 api 연결
- 장소 삭제 api 연결

[NETWORK] 여행지 삭제, 장소 삭제

---

app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/res/layout/fragment_around_place.xml
app/src/main/res/layout/fragment_place_detail.xml

close #171 
- 장소 상세 더보기 버튼 로직 처리
- 여행지 상세 더보기, 플로팅 버튼 로직 처리

[FEAT] 플로팅 버튼, 더보기 버튼 

---

app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/MoreBottomSheetFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt
app/src/main/res/layout/fragment_user_profile.xml

close #175 
- 여행지 상세에서 장소 지도로 보기, 신고 바텀 시트로
- 장소 상세에서 신고 바텀 시트로
- 유저 신고 다이얼로그 연결

[UI] 신고 UI

---

app/src/main/java/com/starters/yeogida/data/api/UserService.kt
app/src/main/java/com/starters/yeogida/data/remote/request/ReportRequest.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/PlaceDetailFragment.kt
app/src/main/java/com/starters/yeogida/presentation/user/profile/UserProfileFragment.kt

close #179 
- 여행지 신고 api 연결
- 장소 신고 api 연결
- 댓글 신고 api 연결
- 유저 신고 api 연결

[NETWORK] 신고

---

app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
app/src/main/res/layout/fragment_add_place.xml

close #127 
- mapView 추가
- 장소 선택에 따른 mapView visibility 변경
- 장소 선택하면 마커 표시

[FEAT] 장소 추가 시 장소 마커 찍기

---

app/src/main/java/com/starters/yeogida/data/api/TripService.kt
app/src/main/java/com/starters/yeogida/presentation/around/AroundPlaceFragment.kt
app/src/main/java/com/starters/yeogida/presentation/around/TripLikeUserFragment.kt
app/src/main/java/com/starters/yeogida/presentation/follow/FollowFragment.kt
app/src/main/java/com/starters/yeogida/presentation/like/LikeTripFragment.kt
app/src/main/java/com/starters/yeogida/presentation/place/AddPlaceFragment.kt
app/src/main/res/layout/fragment_my_comment_place.xml
app/src/main/res/layout/fragment_my_trip.xml

close #183 
- 여기 좋아, 팔로잉, 팔로워 리스트 쌓이던 점 수정
- 장소 추가 후 Context 관련 튕기던 버그 수정
- 여행지 상세 받아올 때, bearerToken 추가
- 엠티뷰 마진 값 조정

[FIX] 데모 관련 버그 수정
